name: Rename Images and Update READMEs

on:
  push:
  workflow_dispatch:

jobs:
  update-favicon:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run Python script
        run: python main.py

      - name: Commit and push if 
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -m "feat/docs: rename images and update READMEs [ci skip]"
            git push
          else
            echo "No changes to commit."
          fi
